# Generated by Django 3.1.2 on 2020-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('comment', models.TextField(verbose_name='Коммент')),
            ],
            options={
                'verbose_name': 'Заявка cо страницы контактов',
                'verbose_name_plural': 'Заявка со страницы контактов',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': 'shop'},
        ),
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
